#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: cmake
# autospec version: v10
# autospec commit: 5905be9
#
# Source0 file verified with key 0x2C8DF587A6D4AAC1 (nicolas.fella@kde.org)
#
Name     : kstatusnotifieritem
Version  : 6.2.0
Release  : 6
URL      : https://download.kde.org/stable/frameworks/6.2/kstatusnotifieritem-6.2.0.tar.xz
Source0  : https://download.kde.org/stable/frameworks/6.2/kstatusnotifieritem-6.2.0.tar.xz
Source1  : https://download.kde.org/stable/frameworks/6.2/kstatusnotifieritem-6.2.0.tar.xz.sig
Source2  : 2C8DF587A6D4AAC1.pkey
Summary  : No detailed summary available
Group    : Development/Tools
License  : CC0-1.0 LGPL-2.0
Requires: kstatusnotifieritem-data = %{version}-%{release}
Requires: kstatusnotifieritem-lib = %{version}-%{release}
Requires: kstatusnotifieritem-license = %{version}-%{release}
BuildRequires : buildreq-cmake
BuildRequires : buildreq-kde
BuildRequires : extra-cmake-modules-data
BuildRequires : gnupg
BuildRequires : libX11-dev libICE-dev libSM-dev libXau-dev libXcomposite-dev libXcursor-dev libXdamage-dev libXdmcp-dev libXext-dev libXfixes-dev libXft-dev libXi-dev libXinerama-dev libXi-dev libXmu-dev libXpm-dev libXrandr-dev libXrender-dev libXres-dev libXScrnSaver-dev libXt-dev libXtst-dev libXv-dev libXxf86vm-dev
BuildRequires : qt6base-dev
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
No detailed description available

%package data
Summary: data components for the kstatusnotifieritem package.
Group: Data

%description data
data components for the kstatusnotifieritem package.


%package dev
Summary: dev components for the kstatusnotifieritem package.
Group: Development
Requires: kstatusnotifieritem-lib = %{version}-%{release}
Requires: kstatusnotifieritem-data = %{version}-%{release}
Provides: kstatusnotifieritem-devel = %{version}-%{release}
Requires: kstatusnotifieritem = %{version}-%{release}

%description dev
dev components for the kstatusnotifieritem package.


%package lib
Summary: lib components for the kstatusnotifieritem package.
Group: Libraries
Requires: kstatusnotifieritem-data = %{version}-%{release}
Requires: kstatusnotifieritem-license = %{version}-%{release}

%description lib
lib components for the kstatusnotifieritem package.


%package license
Summary: license components for the kstatusnotifieritem package.
Group: Default

%description license
license components for the kstatusnotifieritem package.


%prep
mkdir .gnupg
chmod 700 .gnupg
gpg --homedir .gnupg --import %{SOURCE2}
gpg --homedir .gnupg --status-fd 1 --verify %{SOURCE1} %{SOURCE0} > gpg.status
grep -E '^\[GNUPG:\] (GOODSIG|EXPKEYSIG) 2C8DF587A6D4AAC1' gpg.status
%setup -q -n kstatusnotifieritem-6.2.0
cd %{_builddir}/kstatusnotifieritem-6.2.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1715652586
mkdir -p clr-build
pushd clr-build
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export GOAMD64=v2
%cmake ..
make  %{?_smp_mflags}
popd

%install
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export SOURCE_DATE_EPOCH=1715652586
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/kstatusnotifieritem
cp %{_builddir}/kstatusnotifieritem-%{version}/LICENSES/CC0-1.0.txt %{buildroot}/usr/share/package-licenses/kstatusnotifieritem/82da472f6d00dc5f0a651f33ebb320aa9c7b08d0 || :
cp %{_builddir}/kstatusnotifieritem-%{version}/LICENSES/LGPL-2.0-or-later.txt %{buildroot}/usr/share/package-licenses/kstatusnotifieritem/5c6c38fa1b6ac7c66252c83d1203e997ae3d1c98 || :
export GOAMD64=v2
GOAMD64=v2
pushd clr-build
%make_install
popd

%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/dbus-1/interfaces/kf6_org.kde.StatusNotifierItem.xml
/usr/share/dbus-1/interfaces/kf6_org.kde.StatusNotifierWatcher.xml
/usr/share/locale/ar/LC_MESSAGES/kstatusnotifieritem6_qt.qm
/usr/share/locale/ast/LC_MESSAGES/kstatusnotifieritem6_qt.qm
/usr/share/locale/ca/LC_MESSAGES/kstatusnotifieritem6_qt.qm
/usr/share/locale/ca@valencia/LC_MESSAGES/kstatusnotifieritem6_qt.qm
/usr/share/locale/cs/LC_MESSAGES/kstatusnotifieritem6_qt.qm
/usr/share/locale/de/LC_MESSAGES/kstatusnotifieritem6_qt.qm
/usr/share/locale/eo/LC_MESSAGES/kstatusnotifieritem6_qt.qm
/usr/share/locale/es/LC_MESSAGES/kstatusnotifieritem6_qt.qm
/usr/share/locale/eu/LC_MESSAGES/kstatusnotifieritem6_qt.qm
/usr/share/locale/fi/LC_MESSAGES/kstatusnotifieritem6_qt.qm
/usr/share/locale/fr/LC_MESSAGES/kstatusnotifieritem6_qt.qm
/usr/share/locale/gl/LC_MESSAGES/kstatusnotifieritem6_qt.qm
/usr/share/locale/he/LC_MESSAGES/kstatusnotifieritem6_qt.qm
/usr/share/locale/hu/LC_MESSAGES/kstatusnotifieritem6_qt.qm
/usr/share/locale/ia/LC_MESSAGES/kstatusnotifieritem6_qt.qm
/usr/share/locale/is/LC_MESSAGES/kstatusnotifieritem6_qt.qm
/usr/share/locale/it/LC_MESSAGES/kstatusnotifieritem6_qt.qm
/usr/share/locale/ja/LC_MESSAGES/kstatusnotifieritem6_qt.qm
/usr/share/locale/ka/LC_MESSAGES/kstatusnotifieritem6_qt.qm
/usr/share/locale/ko/LC_MESSAGES/kstatusnotifieritem6_qt.qm
/usr/share/locale/lt/LC_MESSAGES/kstatusnotifieritem6_qt.qm
/usr/share/locale/lv/LC_MESSAGES/kstatusnotifieritem6_qt.qm
/usr/share/locale/nl/LC_MESSAGES/kstatusnotifieritem6_qt.qm
/usr/share/locale/nn/LC_MESSAGES/kstatusnotifieritem6_qt.qm
/usr/share/locale/pl/LC_MESSAGES/kstatusnotifieritem6_qt.qm
/usr/share/locale/pt_BR/LC_MESSAGES/kstatusnotifieritem6_qt.qm
/usr/share/locale/ro/LC_MESSAGES/kstatusnotifieritem6_qt.qm
/usr/share/locale/ru/LC_MESSAGES/kstatusnotifieritem6_qt.qm
/usr/share/locale/sa/LC_MESSAGES/kstatusnotifieritem6_qt.qm
/usr/share/locale/sk/LC_MESSAGES/kstatusnotifieritem6_qt.qm
/usr/share/locale/sl/LC_MESSAGES/kstatusnotifieritem6_qt.qm
/usr/share/locale/ta/LC_MESSAGES/kstatusnotifieritem6_qt.qm
/usr/share/locale/tr/LC_MESSAGES/kstatusnotifieritem6_qt.qm
/usr/share/locale/uk/LC_MESSAGES/kstatusnotifieritem6_qt.qm
/usr/share/locale/zh_CN/LC_MESSAGES/kstatusnotifieritem6_qt.qm
/usr/share/locale/zh_TW/LC_MESSAGES/kstatusnotifieritem6_qt.qm
/usr/share/qlogging-categories6/kstatusnotifieritem.categories

%files dev
%defattr(-,root,root,-)
/usr/include/KF6/KStatusNotifierItem/KStatusNotifierItem
/usr/include/KF6/KStatusNotifierItem/kstatusnotifieritem.h
/usr/include/KF6/KStatusNotifierItem/kstatusnotifieritem_export.h
/usr/include/KF6/KStatusNotifierItem/kstatusnotifieritem_version.h
/usr/lib64/cmake/KF6StatusNotifierItem/KF6StatusNotifierItemConfig.cmake
/usr/lib64/cmake/KF6StatusNotifierItem/KF6StatusNotifierItemConfigVersion.cmake
/usr/lib64/cmake/KF6StatusNotifierItem/KF6StatusNotifierItemTargets-relwithdebinfo.cmake
/usr/lib64/cmake/KF6StatusNotifierItem/KF6StatusNotifierItemTargets.cmake
/usr/lib64/libKF6StatusNotifierItem.so

%files lib
%defattr(-,root,root,-)
/usr/lib64/libKF6StatusNotifierItem.so.6
/usr/lib64/libKF6StatusNotifierItem.so.6.2.0

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/kstatusnotifieritem/5c6c38fa1b6ac7c66252c83d1203e997ae3d1c98
/usr/share/package-licenses/kstatusnotifieritem/82da472f6d00dc5f0a651f33ebb320aa9c7b08d0
